In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("sales_data.csv")

In [3]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

In [4]:
df.shape

(76000, 16)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76000 entries, 0 to 75999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                76000 non-null  object
 1   Store ID            76000 non-null  object
 2   Product ID          76000 non-null  object
 3   Category            76000 non-null  object
 4   Region              76000 non-null  object
 5   Inventory Level     76000 non-null  int64
 6   Units Sold          76000 non-null  int64
 7   Units Ordered       76000 non-null  int64
 8   Price               76000 non-null  float64
 9   Discount            76000 non-null  int64
 10  Weather Condition   76000 non-null  object
 11  Promotion           76000 non-null  int64
 12  Competitor Pricing  76000 non-null  float64
 13  Seasonality         76000 non-null  object
 14  Epidemic            76000 non-null  int64
 15  Demand              76000 non-null  int64
dtypes: float64(2), int64(7), object(7)
memory usage: 9.3+ MB

In [6]:
df.isnull().any()

Date                  False
Store ID              False
Product ID            False
Category              False
Region                False
Inventory Level       False
Units Sold            False
Units Ordered         False
Price                 False
Discount              False
Weather Condition     False
Promotion             False
Competitor Pricing    False
Seasonality           False
Epidemic              False
Demand                False
dtype: bool

In [7]:
df["Date"] = pd.to_datetime(df["Date"])

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["DayOfWeek"] = df["Date"].dt.dayofweek


df.drop("Date", axis=1, inplace=True)

In [8]:
df

,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand,Year,Month,Day,DayOfWeek
0,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115,2022,1,1,5
1,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229,2022,1,1,5
2,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157,2022,1,1,5
3,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52,2022,1,1,5
4,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59,2022,1,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75995,S005,P0016,Toys,North,233,63,0,29.80,5,Snowy,0,32.23,Winter,0,64,2024,1,30,1
75996,S005,P0017,Toys,North,137,115,141,42.92,5,Snowy,0,40.73,Winter,0,137,2024,1,30,1
75997,S005,P0018,Clothing,North,197,44,0,17.81,10,Snowy,0,19.41,Winter,0,68,2024,1,30,1
75998,S005,P0019,Furniture,North,125,58,0,151.72,0,Snowy,0,143.71,Winter,0,84,2024,1,30,1
75999,S005,P0020,Toys,North,126,63,59,25.78,10,Snowy,0,29.32,Winter,0,73,2024,1,30,1

In [9]:
df['Weather Condition'].unique()

array(['Snowy', 'Cloudy', 'Sunny', 'Rainy'], dtype=object)

In [10]:
df['Seasonality'].unique()

array(['Winter', 'Spring', 'Summer', 'Autumn'], dtype=object)

In [11]:
df['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [12]:
df['Category'].unique()

array(['Electronics', 'Clothing', 'Groceries', 'Toys', 'Furniture'],
      dtype=object)

In [13]:
df['Store ID'].unique()

array(['S001', 'S002', 'S003', 'S004', 'S005'], dtype=object)

In [14]:
df['Product ID'].unique()

array(['P0001', 'P0002', 'P0003', 'P0004', 'P0005', 'P0006', 'P0007',
       'P0008', 'P0009', 'P0010', 'P0011', 'P0012', 'P0013', 'P0014',
       'P0015', 'P0016', 'P0017', 'P0018', 'P0019', 'P0020'], dtype=object)

In [15]:
numeric_cols = [
    "Inventory Level",
    "Units Sold",
    "Units Ordered",
    "Price",
    "Discount",
    "Competitor Pricing",
    "Year",
    "Month",
    "Day",
    "DayOfWeek",
]

target_encode_cols = [
    "Store ID",
    "Product ID"
]

onehot_cols = [
    "Category",
    "Region",
    "Weather Condition",
    "Promotion",
    "Seasonality",
    "Epidemic"
]

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder,TargetEncoder

In [17]:
preprocessor=ColumnTransformer(
    transformers=[
        ("Scaler",StandardScaler(),numeric_cols),
        ("onehot",OneHotEncoder(),onehot_cols),
        ("target",TargetEncoder(
            target_type="continuous",
            smooth="auto",
            cv=5
        ),target_encode_cols)
    ]
)

In [18]:
X=df.drop('Demand',axis=1)
y=df['Demand']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [41]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_squared_error,root_mean_squared_error

In [42]:
linear_model=Pipeline([
    ("preprocessor",preprocessor),
    ("model",LinearRegression())
])

In [43]:
randomForestModel=Pipeline([
    ("preprcessor",preprocessor),
    ("tree",RandomForestRegressor(n_estimators=200,random_state=42,n_jobs=-1))
])

In [44]:
xgboostModel=Pipeline([
   ("preprcessor",preprocessor),
    ("booster",XGBRegressor(n_estimators=200,max_depth=7,learning_rate=0.05,random_state=42,n_jobs=-1))
])

In [45]:
linear_model.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('Scaler', StandardScaler(),
                                                  ['Inventory Level',
                                                   'Units Sold',
                                                   'Units Ordered', 'Price',
                                                   'Discount',
                                                   'Competitor Pricing', 'Year',
                                                   'Month', 'Day',
                                                   'DayOfWeek']),
                                                 ('onehot', OneHotEncoder(),
                                                  ['Category', 'Region',
                                                   'Weather Condition',
                                                   'Promotion', 'Seasonality',
                                                   'Epidemic']),
                                                 ('target',
                                                  TargetEncoder(target_type='continuous'),
                                                  ['Store ID',
                                                   'Product ID'])])),
                ('model', LinearRegression())])

In [46]:
randomForestModel.fit(x_train,y_train)

Pipeline(steps=[('preprcessor',
                 ColumnTransformer(transformers=[('Scaler', StandardScaler(),
                                                  ['Inventory Level',
                                                   'Units Sold',
                                                   'Units Ordered', 'Price',
                                                   'Discount',
                                                   'Competitor Pricing', 'Year',
                                                   'Month', 'Day',
                                                   'DayOfWeek']),
                                                 ('onehot', OneHotEncoder(),
                                                  ['Category', 'Region',
                                                   'Weather Condition',
                                                   'Promotion', 'Seasonality',
                                                   'Epidemic']),
                                                 ('target',
                                                  TargetEncoder(target_type='continuous'),
                                                  ['Store ID',
                                                   'Product ID'])])),
                ('tree',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])

In [47]:
xgboostModel.fit(x_train,y_train)

Pipeline(steps=[('preprcessor',
                 ColumnTransformer(transformers=[('Scaler', StandardScaler(),
                                                  ['Inventory Level',
                                                   'Units Sold',
                                                   'Units Ordered', 'Price',
                                                   'Discount',
                                                   'Competitor Pricing', 'Year',
                                                   'Month', 'Day',
                                                   'DayOfWeek']),
                                                 ('onehot', OneHotEncoder(),
                                                  ['Category', 'Region',
                                                   'Weather Condition',
                                                   'Promotion', 'Seasonality',
                                                   'Epidemic']),
                                                 ('target',
                                                  TargetEncoder(target_type=...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=7, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=200, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [48]:
linear_pred=linear_model.predict(x_test)

In [49]:
r2_score(y_test,linear_pred)

0.7819158210433654

In [50]:
randomForest_pred=randomForestModel.predict(x_test)

In [51]:
r2_score(y_test,randomForest_pred)

0.8713472096447842

In [32]:
xgboost_pred=xgboostModel.predict(x_test)

In [33]:
r2_score(y_test,xgboost_pred)

0.8859210014343262

In [34]:
mean_squared_error(y_test,linear_pred)

481.63609444047785

In [52]:
root_mean_squared_error(y_test,linear_pred)

21.946351521579636

In [54]:
mean_squared_error(y_test,randomForest_pred)

284.1317144046053

In [55]:
root_mean_squared_error(y_test,randomForest_pred)

16.85620699934019

In [36]:
mean_squared_error(y_test,xgboost_pred)

251.9451904296875

In [56]:
root_mean_squared_error(y_test,xgboost_pred)

15.872781753540039

In [57]:
import joblib

In [58]:
joblib.dump(xgboostModel,"xgboost.pkl")

['xgboost.pkl']

In [59]:
joblib.dump(randomForestModel,"randomforest.pkl")

['randomforest.pkl']

In [60]:
joblib.dump(linear_model,"linearModel.pkl")

['linearModel.pkl']